# kNN as a Classification Algorithm

In [12]:
import inspect
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [4]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [5]:
dataset = pd.read_csv(path, names = headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
X = dataset.iloc[:, :-1].values #features values that we are selecting
y = dataset.iloc[:, 4].values #Target class of the Iris species

#dataframe.iloc ==>> Purely integer-location based indexing for selection by position.
#further information https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

In [8]:
#Standardize features by removing the mean and scaling to unit variance.
#z = (x - u) / s
#futher information ==> https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [10]:
y_pred = classifier.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[22  0  0]
 [ 0 17  0]
 [ 0  3 18]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.85      1.00      0.92        17
 Iris-virginica       1.00      0.86      0.92        21

       accuracy                           0.95        60
      macro avg       0.95      0.95      0.95        60
   weighted avg       0.96      0.95      0.95        60

Accuracy: 0.95


# kNN as a Classification Algorithm

#### Step 1. Load the target dataset
#### Step 2. Perform Preprocessing
#### Step 3. Visualize the correlations and select dependent and independent features
#### Step 4. import the kNN regressor from sklearn and fit this model.
#### Step 5. Evaluate on the basis of MSE and R2.
